# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.


# Daily scraping
name: Global Merchandise Trade

on:
  schedule:
    - cron: "0 2 * * *" # every day at 2 am
 
#on:
#  push:
#   branches: [main, master]
#  pull_request:
#    branches: [main, master]


jobs:
  autoscrape:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages("dplyr")'
        
    - name: Delete old file
      run: |
        R -e 'unlink("Data/Global_Merchandise_Trade.xlsx")'
        
    #- name: Remove file
    #  run: git rm Data/Global_Merchandise_Trade.xlsx
   
    # Run R script
    - name: Global Merchandise Trade
      run: Rscript Global_Merchandise_Trade.R
      
    - name: Add timestamp
      run: echo "Global Merchandise Trade Last updated:$(date)" >> README.md
      

    # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name github-actions
        git config --local user.email "actions@github.com"
        git pull
        git add Data/*
        git commit -am "GH ACTION Autorun $(date)" --allow-empty
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
